# biblio-glutton back-end configuration

# path to ISTEX data
istexDirectory: ../data/istex

# path to the PMC data
pmcDirectory: ../data/pmc

# path to the pubmed data
#pubmedDirectory: ../data/pubmed
pubmedDirectory: /mnt/data/biblio/medline2020

# path to the LMDB databases 
dbDirectory: /media/lopez/T5/data2/db
#dbDirectory: /mnt/data/biblio/db

# elasticsearch server
esHost: localhost
esPort: 9200
esIndexName: pubmed
esClusterName: glutton
